branch-defaults:
  master:
    environment: CoindcxStaging-external
environment-defaults:
  CoindcxStaging-external:
    branch: null
    repository: null
global:
  application_name: coinDCX-Staging
  default_ec2_keyname: coindcx
  default_platform: arn:aws:elasticbeanstalk:ap-south-1::platform/Passenger with Ruby
    2.5 running on 64bit Amazon Linux/2.8.7
  default_region: ap-south-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
