# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  database: <%= ENV['DB_NAME'] %>
  host:     <%= ENV['DB_HOST'] %>
  port:     <%= ENV['DB_PORT'] %>
  pool:     5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>


production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  host:     <%= ENV['RDS_DB_HOST'] %>
  username: <%= ENV['RDS_DB_USERNAME'] %>
  password: <%= ENV['RDS_DB_PASSWORD'] %>
  pool: 15

staging:
  <<: *default
  port:     <%= ENV['RDS_DB_PORT'] %>
  database: <%= ENV['RDS_DB_NAME'] %>
  host:     <%= ENV['RDS_DB_HOST'] %>
  username: <%= ENV['RDS_DB_USERNAME'] %>
  password: <%= ENV['RDS_DB_PASSWORD'] %>

development:
  adapter: postgresql
  database: coindcx_dev
  host: localhost
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  adapter: postgresql
  database: coindcx_test
  host: localhost
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
